//Icons in alphabetical order
import { 
    faBook,
    faChalkboard,
    faCheck, 
    faChevronDown, 
    faChevronLeft, 
    faChevronRight, 
    faChevronUp, 
    faClipboard, 
    faColumns, 
    faCompress, 
    faCopy, 
    faEdit, 
    faExpand, 
    faExternalLinkAlt, 
    faEye, 
    faFile, 
    faFileAlt, 
    faFileArchive, 
    faFileAudio, 
    faFileCode,
    faFileExcel, 
    faFileImage, 
    faFileImport,
    faFileLines,
    faFilePowerpoint, 
    faFileVideo,
    faFileWord,
    faFileZipper,
    faFolder, 
    faFolderPlus, 
    faHardDrive,
    faHeart, 
    faImage, 
    faList, 
    faPager, 
    faPlusSquare,
    faRightFromBracket,
    faRightToBracket,
    faSearchMinus, 
    faSearchPlus,
    faSlash,
    faStar,
    faTable, 
    faTimes, 
    faTrash, 
    faWindowClose,
    faWindowMaximize,
    faWindowMinimize,
    faWindowRestore,
} from "@fortawesome/free-solid-svg-icons";

import ImageCache from './imageCache';
export const cache = ImageCache;

export default [
    faBook,
    faChalkboard,
    faCheck, 
    faChevronDown, 
    faChevronLeft,
    faChevronRight, 
    faChevronUp, 
    faClipboard,
    faColumns,
    faCompress,
    faCopy,
    faEdit,
    faEye,
    faExpand,
    faExternalLinkAlt,
    faFile, 
    faFileAlt,
    faFileArchive,
    faFileAudio,
    faFileCode,
    faFileExcel,
    faFileImage,
    faFileImport,
    faFileLines,
    faFilePowerpoint,
    faFileVideo,
    faFileWord,
    faFileZipper,
    faFolder, 
    faFolderPlus, 
    faHardDrive,
    faHeart,
    faImage,
    faList,
    faPager,
    faPlusSquare, 
    faRightFromBracket,
    faRightToBracket,
    faSearchMinus,
    faSearchPlus,
    faSlash,
    faStar,
    faTable,
    faTimes, 
    faTrash,
    faWindowClose,
    faWindowMaximize,
    faWindowMinimize,
    faWindowRestore,
];

let icons = {
    archive: "file-zipper",
    audio: "file-audio",
    book: "book",
    code: "file-code",
    excel: "file-excel",
    image: "file-image",
    text: "file-lines",
    powerpoint: "file-powerpoint",
    video: "file-video",
    word: "file-word",
}

let fileTypes = {
    audio: ['flac', 'mp3', 'wav', 'wma'],
    archive: ['7z', 'rar', 'zip'],
    book: ['epub', 'mobi', 'azw', 'azw3'],
    code: ['bat', 'c', 'cs', 'css', 'cpp', 'h', 'java', 'js', 'json', 'jsx', 'map', 'py', 'ts', 'tsx', 'xml', 'xps'],
    excel: ['xlsx', 'xlsm', 'xlsb', 'xltm', 'xls', 'xlam'],
    image: ['bmp', 'gif', 'ico', 'jpg', 'jpeg', 'png', 'raw', 'svg', 'tiff'],
    powerpoint: ['potm', 'potx', 'ppam', 'ppsm', 'ppsx', 'pptx'],
    text: ['csv', 'db', 'dll', 'ini', 'log', 'odt', 'rtf', 'sav', 'txt',],
    video: ['3gp', 'avi', 'flv', 'mkv', 'mov', 'mp4', 'mpg', 'mpeg', 'wmv'],
    word: ['doc', 'docx', 'docm', 'dotm', 'dotx'],
}

export function addIcon(type, item) {
    if (type === "folder") return type;
    let basename = item.split('.');
    const ext = basename[basename.length - 1].toLowerCase();
    for (let type in fileTypes) {
        if (fileTypes[type].includes(ext)) return icons[type]
    }
    return "file";
}